// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkPmsRSI547jCkH18pxXjxZfwF10TQGdc',
    appId: '1:586351462635:web:18de0d4191cce55ef756ae',
    messagingSenderId: '586351462635',
    projectId: 'puc-reminder-6952a',
    authDomain: 'puc-reminder-6952a.firebaseapp.com',
    storageBucket: 'puc-reminder-6952a.appspot.com',
    measurementId: 'G-96X99RKQ6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXAE6niHYjGKg6HAZbAlQpGM-LVKUNQ9k',
    appId: '1:586351462635:android:a08f71792af5b4bef756ae',
    messagingSenderId: '586351462635',
    projectId: 'puc-reminder-6952a',
    storageBucket: 'puc-reminder-6952a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwmTle_P5CZpV9Kc1xyGl_pZabdO2iKY',
    appId: '1:586351462635:ios:37fe9f0904ef0ec8f756ae',
    messagingSenderId: '586351462635',
    projectId: 'puc-reminder-6952a',
    storageBucket: 'puc-reminder-6952a.appspot.com',
    iosBundleId: 'com.example.puc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwmTle_P5CZpV9Kc1xyGl_pZabdO2iKY',
    appId: '1:586351462635:ios:37fe9f0904ef0ec8f756ae',
    messagingSenderId: '586351462635',
    projectId: 'puc-reminder-6952a',
    storageBucket: 'puc-reminder-6952a.appspot.com',
    iosBundleId: 'com.example.puc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkPmsRSI547jCkH18pxXjxZfwF10TQGdc',
    appId: '1:586351462635:web:bc23e27f8cb36f92f756ae',
    messagingSenderId: '586351462635',
    projectId: 'puc-reminder-6952a',
    authDomain: 'puc-reminder-6952a.firebaseapp.com',
    storageBucket: 'puc-reminder-6952a.appspot.com',
    measurementId: 'G-9EK124Z7E5',
  );

}